name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Power Test
      id: power-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Power Test
        setup-command: pip install -r requirements.txt
        command: python -m pytest tests/test_power.py -v
        timeout: 10
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        POWER-TEST_RESULTS: "${{steps.power-test.outputs.result}}"
      with:
        runners: power-test
